### ISSUE TITLE
CLVTreeScaper does not have a help?

### ISSUE THREAD

**Issue by josephwb** [whuang08/TreeScaper#9]
Tried:

```
./CLVTreeScaper -h
```

and

```
./CLVTreeScaper --help
```

but all I get in return is:

```
error: input error!
```

It would be convenient to add a help menu.

**Comment by whuang08** [comment]
For now, the documentations of the command line version are available on page 38 of the user manual:“TreeScaperManual_v1.0_9.1.pdf”. We will consider to add a help menu. Thanks for the comment.

**Comment by josephwb** [comment]
I understand; it would just be far more convenient if it were (also) available from the command line. I cannot think of a single program in evolutionary biology that does not offer this.

Not trying to be mean (it sounds mean, but I am trying to help), just trying to make it less painful for users.

**Comment by whuang08** [comment]
I totally understand. Your suggestion is very helpful. I also think it is an excellent idea to add a help menu.

**Comment by whuang08** [comment]
A help menu has been added and the Linux binary file has been updated. The MAC binary file will be updated soon.

**Comment by josephwb** [comment]
Looks good.
